---
source_token: "admin"
source_secret: "password"
source_s3_endpoint: "http://192.168.1.1:9000"
source_s3_bucket: "testbucket"
source_s3_region: "us-east-1"
total_files: 3

dest_token: "admin"
dest_secret: "password"
dest_s3_endpoint: "http://192.168.2.2:9000"
dest_s3_bucket: "testbucket"
dest_s3_region: "us-east-1"