---
source_token: "admin"
source_secret: "password"
source_s3_endpoint: "http://127.0.0.1:9000"
source_s3_bucket: "src"
source_s3_region: "us-east-1"

dest_token: "admin"
dest_secret: "password"
dest_s3_endpoint: "http://127.0.0.1:9001"
dest_s3_bucket: "dest"
dest_s3_region: "us-east-1"
